- !include automations/a_6p_low_battery.yaml
- !include automations/a_away.yaml
- !include automations/a_home_after_dark.yaml
- !include automations/a_home_before_dark.yaml
- !include automations/a_kombucha_mat_on.yaml
- !include automations/a_kombucha_mat_off.yaml
- !include automations/a_n7_low_battery.yaml
- !include automations/a_state_refresh.yaml
- !include automations/a_turn_off_fan_cast.yaml
- !include automations/a_turn_off_fan_kodi.yaml
- !include automations/a_turn_on_fan_cast_idle.yaml
- !include automations/a_turn_on_fan_cast_off.yaml
- !include automations/a_turn_on_fan_kodi.yaml
#- !include automations/a_turn_on_fan_roku_idle.yaml
- !include automations/a_turn_on_fan_roku_home.yaml
- !include automations/a_turn_off_fan_roku.yaml
- !include automations/a_bedtime_anthony.yaml
- !include automations/a_awake_anthony.yaml
- !include automations/sunrise.yaml
- !include automations/sunset.yaml
- !include automations/ad_6p_top_off.yaml
- !include automations/ad_6p_charged.yaml
- !include automations/suspend_gigabyte.yaml
- !include automations/cab_lights_off_night.yaml
####HYPERION AUTOMATIONS####
- !include automations/hyperion_mood_blobs_blue.yaml
- !include automations/hyperion_knight_rider.yaml
- !include automations/hyperion_mood_blobs_cold.yaml
- !include automations/hyperion_mood_blobs_full_color.yaml
- !include automations/hyperion_mood_blobs_green.yaml
- !include automations/hyperion_mood_blobs_red.yaml
- !include automations/hyperion_mood_blobs_warm.yaml
- !include automations/hyperion_rainbow_mood.yaml
- !include automations/hyperion_rainbow_swirl.yaml
- !include automations/hyperion_snake.yaml
- !include automations/hyperion_strobe_blue.yaml
- !include automations/hyperion_strobe_white.yaml
- !include automations/hyperion_strobe_raspberry.yaml
- !include automations/hyperion_off.yaml
- !include automations/hyperion_color_traces.yaml
- !include automations/hyperion_snake.yaml
- !include automations/hyperion_cinema_dim_lights.yaml
- !include automations/hyperion_cinema_dim_lights.yaml
- !include automations/hyperion_cinema_brighten_lights.yaml
- !include automations/hyperion_police_lights_single.yaml
- !include automations/hyperion_random.yaml
- !include automations/hyperion_police_lights_solid.yaml
- !include automations/hyperion_running_dots.yaml
- !include automations/hyperion_system_shutdown.yaml
- !include automations/hyperion_sparks_color.yaml
- !include automations/hyperion_sparks.yaml
- !include automations/hyperion_color_traces.yaml
