- platform: mqtt
  name: "bedroom_fan"
  state_topic: "/switches/rf/bedroom_fan/state"
  command_topic: "/switches/rf/bedroom_fan"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: mqtt
  name: "guestroom_fan"
  state_topic: "/switches/rf/guestroom_fan/state"
  command_topic: "/switches/rf/guestroom_fan"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: mqtt
  name: "6p_charger"
  state_topic: "/switches/rf/charger_ad_6p/state"
  command_topic: "/switches/rf/charger_ad_6p"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: mqtt
  name: "kombucha_mat"
  state_topic: "/switches/rf/kombucha_mat/state"
  command_topic: "/switches/rf/kombucha_mat"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: mqtt
  name: "lr_fan"
  state_topic: "/switches/rf/lr_fan/state"
  command_topic: "/switches/rf/lr_fan"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: mqtt
  name: "office_light"
  state_topic: "/switches/rf/office_light/state"
  command_topic: "/switches/rf/office_light"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: mqtt
  name: "ad_nightstand"
  command_topic: "/switches/rf/ad_nightstand"
  state_topic: "/switches/rf/ad_nightstand/state"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: mqtt
  name: "stove_right"
  state_topic: "/lights/kitchen/stoveright/state"
  command_topic: "/lights/kitchen/stoveright"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: mqtt
  name: "stove_left"
  state_topic: "/lights/kitchen/stoveleft/state"
  command_topic: "/lights/kitchen/stoveleft"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: mqtt
  name: "sink_right"
  state_topic: "/lights/kitchen/sinkright/state"
  command_topic: "/lights/kitchen/sinkright"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: mqtt
  name: "sink_left"
  state_topic: "/lights/kitchen/sinkleft/state"
  command_topic: "/lights/kitchen/sinkleft"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: mqtt
  name: "pantry"
  state_topic: "/lights/kitchen/pantry/state"
  command_topic: "/lights/kitchen/pantry"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: mqtt
  name: "Tree Solid Lights"
  state_topic: "/switches/rf/tree_solid/state"
  command_topic: "/switches/rf/tree_solid"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: mqtt
  name: "Tree Twinkle Lights"
  state_topic: "/switches/rf/tree_twinkle/state"
  command_topic: "/switches/rf/tree_twinkle"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 1
  retain: true
- platform: wake_on_lan
  mac_address: "6c-f0-49-0b-97-5c"
  name: "Gigabyte"
  host: "10.10.10.10"
- platform: wake_on_lan
  mac_address: "74-da-38-6d-1f-86"
  name: "Gitlab"
  host: "10.10.10.125"
- platform: wake_on_lan
  mac_address: "CC-52-AF-56-61-5B"
  name: "G7"
  host: "10.10.10.7"
- platform: wake_on_lan
  mac_address: "50-AF-73-24-78-82"
  name: "KODI"
  host: "10.10.10.190"
- platform: wake_on_lan
  mac_address: "00-11-32-41-53-93"
  name: "Synology"
  host: "10.10.10.109"
