alias: "Home before Dark"
trigger:
  platform: state
  entity_id: group.humans
  from: "not_home"
  to: "home"
condition:
  condition: sun
  before: sunset
action:
  service: switch.turn_on
  entity_id:
    - switch.lr_fan
    - switch.bedroom_fan
    - switch.guestroom_fan
    - switch.pantry
