alias: "Turn On Fan - Roku Idle"
trigger:
  platform: state
  entity_id: media_player.roku_yy00dk366469
  state: playing
  for:
    seconds: 0
    minutes: 1
    hours: 0
condition: 
  condition: and
  conditions:
    - condition: state
      entity_id: media_player.roku_yy00dk366469
      state: "playing"
      source: "Nature 4K UHD Screensaver"
    - condition: state
      entity_id: media_player.kodi
      state: "idle"
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.living_room
          state: "idle"
        - condition: state
          entity_id: media_player.living_room
          state: "off"
action:
  service: switch.turn_on
  entity_id: switch.lr_fan
