alias: "Away"
trigger:
  platform: state
  entity_id: group.humans
  from: "home"
  to: "not_home"
action:
  service: switch.turn_off
  entity_id: 
    - switch.lr_fan
    - switch.bedroom_fan
    - switch.guestroom_fan
    - switch.office_light
    - switch.stove_left
    - switch.stove_right
    - switch.sink_right
    - switch.sink_left
    - switch.6p_charger
    - switch.pantry
#    - switch.tree_solid_lights
#    - switch.tree_twinkle_lights
