alias: "Turn On Fan - Kodi"
trigger:
  platform: state
  entity_id: media_player.kodi
  state: "idle"
  for:
    hours: 0
    minutes: 1
    seconds: 0
condition: 
  condition: and
  conditions:
    - condition: state
      entity_id: media_player.roku_yy00dk366469
      state: "home"
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.living_room
          state: "idle"
        - condition: state
          entity_id: media_player.living_room
          state: "off"
action:
  service: switch.turn_on
  entity_id: switch.lr_fan
