alias: "Turn On Fan - Cast Idle"
trigger:
  platform: state
  entity_id: media_player.living_room
  state: "idle"
  for:
    seconds: 0
    minutes: 1
    hours: 0
condition: 
  condition: and
  conditions:
    - condition: state
      entity_id: media_player.roku_yy00dk366469
      state: "home"
    - condition: state
      entity_id: media_player.kodi
      state: "idle"
action:
  service: switch.turn_on
  entity_id: switch.lr_fan
